# Generated by Django 4.0.5 on 2022-07-19 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RootCAIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('certificate', models.TextField(unique=True)),
                ('key', models.TextField(unique=True)),
                ('set_issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ca_intermediate.rootcaim')),
            ],
        ),
    ]
